# Generated by Django 3.1.3 on 2021-04-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunafa', '0002_auto_20210424_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baklawa',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='crunchy_kunafa',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
